server:
  port: 10016

spring:
  #应用名称
  application:
    name: producer-consumer

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hikmaintain?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: RootCC123@
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: guest
    ####密码
    password: guest
    ### 地址
    virtual-host: /
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 3000
        acknowledge-mode: manual

# mybatis 扫描路径
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

#日志级别
logging:
  level:
    root: info
    com.dongl.rabbitmq.mapper: DEBUG
    org.springframework.web: ERROR
    org.springframework: ERROR