
server:
  port: 10017

spring:
  #应用名称
  application:
    name: producer-server

  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: guest
    ####密码
    password: guest
    ### 地址
    virtual-host: /
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 3000
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
    connection-timeout: 15000
    publisher-returns: true
    template:
      mandatory: true

#日志级别
logging:
  level:
    root: info
    com.dongl.rabbitmq.mapper: DEBUG
    org.springframework.web: ERROR
    org.springframework: ERROR